### ISSUE TITLE
Can't get mod list

### ISSUE THREAD

**Issue by Lavalierre** [trade-helper/trade-helper.github.io#2]
Web version can't check for item mods, it's just ignores them
![image](https://user-images.githubusercontent.com/56591132/185736655-6d396715-f9c5-4bd9-a6eb-4d10ec439c1a.png)
![image](https://user-images.githubusercontent.com/56591132/185736679-77e0a24d-0a03-45cb-9a08-644616508d56.png)

**Comment by trade-helper** [comment]
@Lavalierre Are you sure that you are using CTRL + ALT + C instead of regular CTRL + C?
